### ISSUE TITLE
Doesn't seem to work for string type + initial value.

### ISSUE THREAD

**Issue by pjanik** [rehooks/local-storage#53]
If you use this hook and reload a page, the hook will restore the initial value, even though there's a non-null value available in the localStorage.

I think these lines are causing this:
https://github.com/rehooks/local-storage/blob/v2.2.2/src/use-localstorage.ts#L74 (that's what's in the npm currently)
https://github.com/rehooks/local-storage/blob/master/src/use-localstorage.ts#L88
The random string isn't a valid JSON so canWrite will be true.

**Comment by jharrilim** [comment]
I believe this was fixed in this PR:
https://github.com/rehooks/local-storage/pull/48/files

Just has to be published.

**Comment by pjanik** [comment]
I'm not sure about it. I've seen that PR was mostly about boolean values. This line still doesn't seem to support strings:
```javascript
const canWrite = localStorage.getItem(key) === null || !isValidJSON(localStorage.getItem(key)!);
```
Assuming that my local storage item is "foobar", `isValidJSON` will return false, so `canWrite` will be equal to true. And the local storage value will be overwritten a few lines below.

Bascially, I want to use this library in the simplest possible way:

```javascript
const [item] = useLocalStorage("key", "initialValue");
```
No JSONs, no booleans, no parsing, just want to store strings.

**Comment by jharrilim** [comment]
Ah oops, I was under the impression that JSON.parse worked on strings. I was slightly off. This works:

```js
JSON.parse("\"hello world\"")
```
this doesn't:

```js
JSON.parse("Hello world")
```
I'll take a look into fixing it today, sorry about that!

**Comment by jharrilim** [comment]
Sorry about the delay @pjanik, got busy with other stuff

**Comment by pjanik** [comment]
Is this going to be published to npm?

**Comment by iamsolankiamit** [comment]
@pjanik This is published now https://github.com/rehooks/local-storage/releases/tag/v2.4.0 .
