### ISSUE TITLE
TypeError: Class constructor CustomEvent cannot be invoked without 'new'

### ISSUE THREAD

**Issue by cohancarpentier** [rehooks/local-storage#77]
When running tests with Jest & running our app on `"@rehooks/local-storage": "2.4.1"`

Details:
```
     at new LocalStorageChanged (node_modules/@rehooks/local-storage/src/local-storage-events.ts:21:9)
      at Object.writeStorage (node_modules/@rehooks/local-storage/src/local-storage-events.ts:54:30)
      at create (node_modules/@rehooks/local-storage/src/use-localstorage.ts:89:7)
      at apply (node_modules/react-dom/cjs/react-dom.development.js:23487:20)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:315:27)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:266:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:212:11)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
```

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/44584733/115566994-c76d1980-a288-11eb-8340-51a4e86362dd.png">

**Comment by AndreasGJ** [comment]
I have the same error?

**Comment by spencerschack** [comment]
I am having the same issue. For a quickfix you can rollback to 2.4.0. The breaking behavior was introduced by #67. I think the fix would be to implement the suggestion in this comment: https://github.com/rehooks/local-storage/pull/67#issuecomment-668833477

**Comment by AndreasGJ** [comment]
@spencerschack you are a life saver 🥇

**Comment by ckknight** [comment]
Yep, running into this. Reverting to 2.4.0 works.

**Comment by se7entyse7en** [comment]
I can confirm that our CI started failing when we updated from 2.4.0 to 2.4.1.

**Comment by faradaytrs** [comment]
When is that planned to be fixed? 2.4.1 is broken

**Comment by amed** [comment]
Any update on this?

**Comment by maapteh** [comment]
Dead package?

**Comment by jharrilim** [comment]
> I am having the same issue. For a quickfix you can rollback to 2.4.0. The breaking behavior was introduced by #67. I think the fix would be to implement the suggestion in this comment: [#67 (comment)](https://github.com/rehooks/local-storage/pull/67#issuecomment-668833477)

Thanks for suggesting the quickfix!

> Any update on this?

I haven't taken a look at this repo in a while so I might be a bit slow to boot, but I shall look into this tonight or sometime this week.

> @jharrilim is it possible to make at least a working patch version? Everytime when doing a interactive upgrade this lib pops up in not making our build correctly anymore. Its not expectable that using a patch upgrade can give this behaviour. Thanks!

Agreed, and sorry for the inconvenience. We shall fix this sometime soon.

**Comment by jharrilim** [comment]
While I wait on getting access to publish to npmjs.com, I have published the 2.4.2 patch to GitHub packages instead.

For the time being, if you add this to an `.npmrc` file in your repo, you can download from GitHub packages instead:

```
@rehooks:registry=https://npm.pkg.github.com
```

**Comment by davidcostadev** [comment]
Do we have some plans to update the version on the npm?
![image](https://user-images.githubusercontent.com/3098556/130119493-2ef57d8e-e184-4815-880e-3596a15e5f20.png)

**Comment by jharrilim** [comment]
> Do we have some plans to update the version on the npm?
> ![image](https://user-images.githubusercontent.com/3098556/130119493-2ef57d8e-e184-4815-880e-3596a15e5f20.png)

Sorry to say it but it doesn't look like I'll be able to do this any time soon:
https://github.com/rehooks/local-storage/pull/78#issuecomment-886236443
https://github.com/rehooks/local-storage/pull/61#issuecomment-728342394

As mentioned above, however, I have provided 2 viable solutions that were the best I could do for now. Feel free to use those, or fork this repo if those solutions aren't preferable.

**Comment by iamsolankiamit** [comment]
@jharrilim the fix is released under 2.4.3 version on npm. I don't have org access to rehooks to add you as a contributor to npm. Didn't focus on this, as I was busy with my day job and don't really use this package anymore. Thanks for keeping it maintained. I'll try to be more active with publishing.

**Comment by anark** [comment]
I am still seeing this error after upgrading to 2.4.3.  Is there anything else that needs to be done to fix this?

**Comment by samofwise** [comment]
Hey Im also seeing this error on version 2.4.3. Any update on a fix?

**Comment by faradaytrs** [comment]
@samofwise Same here, problem wasn't fixed in 2.4.3, please reopen

**Comment by iamsolankiamit** [comment]
Reopening as it seems the issue is not resolved

**Comment by quolpr** [comment]
Yep, an issue is still here

**Comment by ayozemr** [comment]
same here

**Comment by j05u3** [comment]
> @jharrilim the fix is released under 2.4.3 version on npm. I don't have org access to rehooks to add you as a contributor to npm. Didn't focus on this, as I was busy with my day job and don't really use this package anymore. Thanks for keeping it maintained. I'll try to be more active with publishing.

Thanks!
Btw, out of curiosity, do you use another package or another way to handle reactive local storage? or you just meant you don't code this kind of features anymore.

**Comment by formatlos** [comment]
I do get the same error with 2.4.3, reverting back to 2.4.0 works

**Comment by giladgo** [comment]
Will #80 fix this? Seems that inheriting from `CustomEvent` was removed there...
I was just wondering... when can we expect the next release to npm? :)

**Comment by iamsolankiamit** [comment]
@giladgo 2.4.4 should fix this
